### ISSUE TITLE
Cannot convert value of type ... In AccessTokenEnvelope

### ISSUE THREAD

**Issue by hprobotic** [kickstarter/ios-ksapi#14]
Hi
When i define AccessTokenEnvelope model. I saw this error
Can you explain this 👍 
```
/Users/johnp/Source/iOS/Facestar/Network/lib/AccessTokenEnvelope.swift:20:42: Cannot convert value of type '(String, User) -> AccessTokenEnvelope' to expected argument type '(_) -> (_) -> AccessTokenEnvelope'
```
<img width="1035" alt="screen shot 2017-02-22 at 12 01 13 pm" src="https://cloud.githubusercontent.com/assets/5791885/23198002/dfc2894c-f8f6-11e6-98df-0d5e46d20465.png">

**Comment by mbrandonw** [comment]
Is`User` decodable?

Also, this doesnt seem to be specific to our repo, so gonna close this one.
